plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
//    id 'com.google.dagger.hilt.android'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.0.21'
    id 'com.google.gms.google-services'
    // Add the Crashlytics Gradle plugin
    id 'com.google.firebase.crashlytics'
}

def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))
def razorPayKeyId = localProperties.getProperty("RAZORPAY_KEY_ID") ?: ""

android {
    namespace 'com.example.shoppingapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.shoppingapp"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        buildConfigField(
                "String",
                "RAZORPAY_KEY_ID",
                "\"$razorPayKeyId\""
        )

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
        dataBinding = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout

    // recyclerview dependency
    implementation libs.androidx.recyclerview

    //viewmodel dependencies
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.livedata.ktx

    // navigation component dependencies
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation(libs.kotlinx.serialization.json)

    //coroutines dependencies
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.core

    // network dependencies
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp
    implementation libs.logging.interceptor

    // room dependencies
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime
    kapt libs.androidx.room.compiler

    // glide dependencies
    implementation libs.glide
    kapt libs.glide.compiler

    // dagger dependencies
    implementation libs.dagger
    kapt libs.dagger.compiler

    //hilt dependencies
//    implementation libs.dagger.hilt.android
//    kapt libs.dagger.hilt.compiler

    // Import the Firebase BoM
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.messaging
    implementation libs.firebase.config
    implementation libs.firebase.crashlytics
    implementation libs.firebase.analytics

    //razorpay sdk integration
    implementation libs.razorpay.checkout




    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}